/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./app/**/*.{ts,tsx , jsx , js}",
    "./src/**/*.{ts,tsx}",
  ],
  theme: {
    screens: {
      TABLET: "700px",
      SMALL_LAPTOP: "1031px",
      LAPTOP: "1515px",
      LARGE_LAPTOP: "1925px",
    },

    extend: {
      fontSize: {
        heading: "5.5rem",
        "sub-heading": "4rem",
        "medium-sub-heading": "3rem",
        "small-sub-heading": "2.5rem",
        "large-text": "2rem",
        text: "1.250rem",
        "small-text": "1rem",
        "ss-text": "0.75rem",
        "Mobile-L-Head": "2.5rem",
        "Mobile-S-Heading": "1.25rem",
        "Mobile-Head": "1.5rem",
        "Mobile-Text": "1rem",
        "Mobile-S-Text": "0.75rem",
        "Tablet-L-Head": "5rem",
        "Tablet-S-Heading": "3rem",
        "Tablet-Head": "4rem",
        "Tablet-Subheading": "2.5rem",
        "Tablet-Large-Text": "2rem",
        "Tablet-Text": "1.5rem",
        "Tablet-Small-Text": "1rem",
        "Tablet-Caption": "0.75rem",
        "SMALL_LAPTOP-Heading": "5.5rem",
        "SMALL_LAPTOP-Subheading": "4rem",
        "SMALL_LAPTOP-M-Subheading": "3rem",
        "SMALL_LAPTOP-S-Subheading": "2.5rem",
        "SMALL_LAPTOP-L-Text": "2rem",
        "SMALL_LAPTOP-Text": "1.25rem",
        "SMALL_LAPTOP-S-Text": "1rem",
        "SMALL_LAPTOP-SS-Text": "0.75rem",
      },
      fontWeight: {
        "base-weight": "400",
      },
      colors: {
        themeColorlight: "var(--themeColor-20)",
        themeColor: "var(--themeColor)",
        primaryBackgroundColor: "var(--primaryBackgroundColor)",
        secondaryBackgroundColor: "var(--secondaryBackgroundColor)",
        tertiaryBackgroundColor: "var(--tertiaryBackgroundColor)",
        textPrimaryColor: "var(--textPrimaryColor)",
        textSecondaryColor: "var(--textSecondaryColor)",
        primaryBackgroundColorDark: "var(--primaryBackgroundColorDark)",
        textSecondaryColorLight: "var(--textSecondaryColorLight)",
        tertiaryBackgroundColorLight: "var(--tertiaryBackgroundColorLight)",
        marketingBg: "var(--marketingBg)",
        securityBg: "var(--securityBg)",
        appBg: "var(--appBg)",
        seoBg: "var(--seoBg)",
        webBg: "var(--webBg)",
        uiBg: "var(--uiBg)",
        marketingBorder: "var(--marketingBorder)",
        securityBorder: "var(--securityBorder)",
        appBorder: "var(--appBorder)",
        seoBorder: "var(seoBorder)",
        webBorder: "var(--webBorder)",
        uiBorder: "var(--uiBorder)",
        marketingText: "var(--marketingText)",
        securityText: "var(--securityText)",
        appText: "var(--appText)",
        seoText: "var(--seoText)",
        webText: "var(--webText)",
        uiText: "var(--uiText)",
      },

      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: 0 },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: 0 },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
};
