'use client'
import './globals.css'
import type { Metadata } from 'next'
import { Poppins } from 'next/font/google'
import { ThemeProvider } from "next-themes";
import Navbar from '@/components/Navbar';
import Footer from '@/components/Footer';
import Prefooter from '@/components/Prefooter';
const inter = Poppins({
  weight: '400',
  subsets: ["latin" , "latin" , "latin-ext"],
  display: 'swap',
})
// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={inter.className}>
        <ThemeProvider  attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>
          {/* <Navbar />
        <Prefooter />
        <Footer /> */}
        {children}


        </ThemeProvider>
        
        </body>
    </html>
  )
}
